'use client';

import { useState } from 'react';
import { ChevronDown, MessageCircle, Search, ShoppingBag, CreditCard, Bike, RotateCcw, UserRound } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
const topics = [{ label: 'Order issue', icon: ShoppingBag }, { label: 'Payment issue', icon: CreditCard }, { label: 'Delivery problem', icon: Bike }, { label: 'Refund', icon: RotateCcw }, { label: 'Account problem', icon: UserRound }];
const faqs = ['Where is my order?', 'How can I cancel my order?', 'How do refunds work?', 'How can I change my address?', 'How can I contact the delivery partner?'];
export default function HelpPage() { const [open, setOpen] = useState<string | null>(null); const [query, setQuery] = useState(''); const visible = faqs.filter((faq) => faq.toLowerCase().includes(query.toLowerCase())); return <div className="mx-auto max-w-5xl px-4 py-6 lg:px-8"><div className="rounded-3xl bg-gradient-to-br from-primary to-primary-dark px-6 py-10 text-white sm:px-10"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-white/75">Support center</p><h1 className="mt-2 font-display text-3xl font-bold">How can we help?</h1><div className="relative mt-6 max-w-2xl"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your question..." className="h-12 rounded-full border-0 bg-white pl-11 text-foreground" /></div></div><h2 className="mt-9 font-display text-xl font-bold">What do you need help with?</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{topics.map(({ label, icon: Icon }) => <button key={label} onClick={() => toast.success(`${label} support selected`)} className="rounded-2xl border border-border/60 bg-card p-4 text-center transition-all hover:-translate-y-1 hover:border-primary"><Icon className="mx-auto h-6 w-6 text-primary" /><span className="mt-2 block text-sm font-medium">{label}</span></button>)}</div><div className="mt-9 grid gap-6 lg:grid-cols-[1fr_300px]"><div><h2 className="font-display text-xl font-bold">Frequently asked questions</h2><div className="mt-4 divide-y divide-border rounded-2xl border border-border/60 bg-card">{visible.map((faq) => <button key={faq} onClick={() => setOpen(open === faq ? null : faq)} className="flex w-full items-center gap-3 p-5 text-left"><span className="flex-1 font-medium">{faq}</span><ChevronDown className={cn('h-4 w-4 transition-transform', open === faq && 'rotate-180')} />{open === faq && <span className="absolute" />}</button>)}</div></div><div className="h-fit rounded-2xl border border-border/60 bg-card p-5"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><MessageCircle className="h-6 w-6" /></div><h3 className="mt-4 font-display text-lg font-bold">Still need help?</h3><p className="mt-2 text-sm text-muted-foreground">Our support team is available 24/7 for you.</p><Button className="mt-4 w-full" onClick={() => toast.success('Chat support opened')}>Contact Support</Button></div></div></div>; }
