'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, Bike, Download, HelpCircle, MapPin, Receipt, Store } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { orders, formatPrice } from '@/lib/data';
import { toast } from 'sonner';

export default function OrderDetailsPage() {
  const params = useParams();
  const order = orders.find((entry) => entry.id === params.id) ?? orders[0];
  return <div className="mx-auto max-w-4xl px-4 py-6 lg:px-8"><Link href="/orders" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" /> Back to orders</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Order details</p><h1 className="mt-1 font-display text-3xl font-bold">{order.id}</h1><p className="mt-1 text-sm text-muted-foreground">Placed on {order.date}</p></div><div className="flex gap-2">{order.status !== 'delivered' && order.status !== 'cancelled' && <Link href={`/orders/${order.id}/track`}><Button><Bike className="mr-2 h-4 w-4" /> Track</Button></Link>}<Button variant="outline" onClick={() => toast.success('Invoice download started')}><Download className="mr-2 h-4 w-4" /> Invoice</Button></div></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_300px]"><div className="space-y-5"><div className="rounded-2xl border border-border/60 bg-card p-5"><div className="flex items-center gap-3"><img src={order.restaurantLogo} alt="" className="h-12 w-12 rounded-xl object-cover" /><div><h2 className="font-display font-semibold">{order.restaurant}</h2><p className="text-sm text-muted-foreground">Your order</p></div></div><div className="mt-5 space-y-4">{order.items.map((item) => <div key={item.name} className="flex justify-between text-sm"><span>{item.quantity} × {item.name}</span><span className="font-medium">{formatPrice(item.price * item.quantity)}</span></div>)}</div></div><div className="rounded-2xl border border-border/60 bg-card p-5"><h2 className="font-display font-semibold">Delivery address</h2><p className="mt-3 flex gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0 text-primary" /> {order.address}</p></div><div className="rounded-2xl border border-border/60 bg-card p-5"><h2 className="font-display font-semibold">Need help?</h2><p className="mt-2 text-sm text-muted-foreground">Our support team is ready to help with your order.</p><Link href="/help"><Button variant="outline" className="mt-4"><HelpCircle className="mr-2 h-4 w-4" /> Get Help</Button></Link></div></div><div className="h-fit rounded-2xl border border-border/60 bg-card p-5"><h2 className="font-display font-semibold">Payment summary</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Item total</span><span>{formatPrice(order.total - 50)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Delivery & fees</span><span>{formatPrice(50)}</span></div><div className="mt-3 flex justify-between border-t border-border pt-3 font-bold"><span>Total</span><span>{formatPrice(order.total)}</span></div></div><p className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><Receipt className="h-4 w-4 text-primary" /> Paid via {order.paymentMethod}</p></div></div></div>;
}
