'use client';

import { useParams } from 'next/navigation';
import { BarChart3, CheckCircle2, ClipboardList, CreditCard, Edit3, LayoutDashboard, MessageSquare, Package, Settings, ShoppingBag, Store, TicketPercent, Users, Bike } from 'lucide-react';
import { PanelShell, MetricCard, type PanelNavItem } from '@/components/panels/panel-shell';
import { Button } from '@/components/ui/button';
import { restaurants, orders, formatPrice } from '@/lib/data';
import { toast } from 'sonner';
const nav: PanelNavItem[] = [{ href: '/admin', label: 'Dashboard', icon: LayoutDashboard }, { href: '/admin/restaurants', label: 'Restaurants', icon: Store }, { href: '/admin/users', label: 'Users', icon: Users }, { href: '/admin/orders', label: 'Orders', icon: Package }, { href: '/admin/products', label: 'Food Items', icon: ShoppingBag }, { href: '/admin/categories', label: 'Categories', icon: LayoutDashboard }, { href: '/admin/coupons', label: 'Coupons', icon: TicketPercent }, { href: '/admin/payments', label: 'Payments', icon: CreditCard }, { href: '/admin/reviews', label: 'Reviews', icon: MessageSquare }, { href: '/admin/delivery-partners', label: 'Delivery Partners', icon: Bike }, { href: '/admin/reports', label: 'Reports', icon: BarChart3 }, { href: '/admin/settings', label: 'Settings', icon: Settings }];
export default function AdminSubPage() { const params = useParams(); const slug = Array.isArray(params.slug) ? params.slug.join('/') : String(params.slug ?? 'restaurants'); const title = slug.split('/').pop()?.replace(/-/g, ' ') ?? 'restaurants'; const rows = title === 'orders' ? orders.map((order) => ({ first: order.id, second: order.restaurant, third: formatPrice(order.total), fourth: order.status })) : restaurants.map((restaurant) => ({ first: restaurant.name, second: restaurant.cuisines.join(' • '), third: restaurant.rating.toFixed(1), fourth: restaurant.isOpen ? 'Approved' : 'Pending' })); return <PanelShell title={title.charAt(0).toUpperCase() + title.slice(1)} subtitle="Manage FoodGo operations with clear, actionable controls." brand="FoodGo Admin" navItems={nav} accent="bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-2xl font-bold">{title} management</h2><p className="mt-1 text-sm text-muted-foreground">Review records, update statuses and keep the marketplace healthy.</p></div><Button onClick={() => toast.success('Create form opened')}>Add new</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><MetricCard label="Total records" value={title === 'orders' ? '3,842' : '1,284'} change="+12.4% this month" icon={ClipboardList} /><MetricCard label="Pending review" value="86" change="Needs attention" icon={Edit3} /><MetricCard label="Resolved today" value="142" change="+8.1% today" icon={CheckCircle2} /></div><div className="mt-6 overflow-x-auto rounded-2xl border border-border/60 bg-card"><div className="grid min-w-[620px] grid-cols-4 gap-4 border-b border-border bg-muted/40 p-4 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><span>{title === 'orders' ? 'Order ID' : 'Name'}</span><span>Details</span><span>{title === 'orders' ? 'Amount' : 'Rating'}</span><span>Status</span></div>{rows.map((row) => <div key={row.first} className="grid min-w-[620px] grid-cols-4 items-center gap-4 border-b border-border p-4 last:border-0"><span className="text-sm font-semibold">{row.first}</span><span className="text-sm text-muted-foreground">{row.second}</span><span className="text-sm font-medium">{row.third}</span><span><span className="rounded-full bg-success/10 px-3 py-1 text-xs font-semibold text-success">{row.fourth}</span></span></div>)}</div></PanelShell>; }
