'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, Bike, CheckCircle2, Clock3, Package, RotateCcw, Star, XCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { orders, formatPrice } from '@/lib/data';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

const tabs = ['All', 'Active', 'Completed', 'Cancelled'];
const statusLabel: Record<string, string> = { 'out-for-delivery': 'Out for delivery', delivered: 'Delivered', cancelled: 'Cancelled' };
export default function OrdersPage() {
  const [active, setActive] = useState('All');
  const filtered = orders.filter((order) => active === 'All' || (active === 'Active' && !['delivered', 'cancelled'].includes(order.status)) || (active === 'Completed' && order.status === 'delivered') || (active === 'Cancelled' && order.status === 'cancelled'));
  return <div className="mx-auto max-w-4xl px-4 py-6 lg:px-8"><h1 className="font-display text-3xl font-bold">My orders</h1><p className="mt-1 text-muted-foreground">Track current orders and reorder your favorites.</p><div className="mt-6 flex gap-2 border-b border-border">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={cn('border-b-2 px-3 pb-3 text-sm font-medium', active === tab ? 'border-primary text-primary' : 'border-transparent text-muted-foreground')}>{tab}</button>)}</div><div className="mt-5 space-y-4">{filtered.map((order) => <div key={order.id} className="rounded-2xl border border-border/60 bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-3"><img src={order.restaurantLogo} alt="" className="h-12 w-12 rounded-xl object-cover" /><div><h2 className="font-display font-semibold">{order.restaurant}</h2><p className="mt-1 text-xs text-muted-foreground">{order.date} • {order.id}</p></div></div><span className={cn('flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold', order.status === 'cancelled' ? 'bg-destructive/10 text-destructive' : order.status === 'delivered' ? 'bg-success/10 text-success' : 'bg-primary/10 text-primary')}>{order.status === 'cancelled' ? <XCircle className="h-3.5 w-3.5" /> : order.status === 'delivered' ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Bike className="h-3.5 w-3.5" />}{statusLabel[order.status] ?? order.status}</span></div><div className="mt-4 border-t border-border pt-4 text-sm"><p>{order.items.map((item) => `${item.quantity} × ${item.name}`).join(', ')}</p><div className="mt-2 flex items-center justify-between"><span className="text-muted-foreground">{order.paymentMethod}</span><span className="font-bold">{formatPrice(order.total)}</span></div></div><div className="mt-4 flex flex-wrap gap-2">{order.status !== 'delivered' && order.status !== 'cancelled' && <Link href={`/orders/${order.id}/track`}><Button size="sm"><Bike className="mr-1 h-4 w-4" /> Track Order</Button></Link>}<Link href={`/orders/${order.id}`}><Button size="sm" variant="outline">View Details <ArrowRight className="ml-1 h-4 w-4" /></Button></Link>{order.status === 'delivered' && <Button size="sm" variant="outline" onClick={() => toast.success('Your previous items were added to the cart')}><RotateCcw className="mr-1 h-4 w-4" /> Reorder</Button>}{order.status === 'delivered' && <Button size="sm" variant="ghost" onClick={() => toast.success('Thanks for your rating')}><Star className="mr-1 h-4 w-4" /> Rate Order</Button>}</div></div>)}</div></div>;
}
